name: GitHub Classroom Workflow

on: [push]

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
        - name: Install PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: '7.3'
            tools: phpunit:9.5.28

        - name: Actions 
          uses: actions/checkout@v2

        - name: Education
          uses: education/autograding@v1
